# Default values for memcached.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

images:
  entrypoint: quay.io/stackanetes/kubernetes-entrypoint:v0.1.0
  horizon: quay.io/stackanetes/stackanetes-horizon:newton
  pull_policy: "IfNotPresent"

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port: 80

local_settings:
  horizon_secret_key: 9aee62c0-5253-4a86-b189-e0fb71fa503c
  debug: "True"

# typically overriden by environmental 
# values, but should include all endpoints
# required by this chart
endpoints:
  keystone:
    hosts:
      default: keystone-api.openstack.cluster.local
    path: /v2.0
    type: identity
    scheme: 'http'
    port:
        admin: 35356
        public: 5000
