# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.conductor }}
{{- $mounts_nova_conductor := .Values.mounts.nova_conductor.nova_conductor }}
{{- $mounts_nova_conductor_init := .Values.mounts.nova_conductor.init_container }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nova-conductor
spec:
  replicas: {{ .Values.replicas.conductor }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}
  template:
    metadata:
      labels:
        app: nova-conductor
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies $mounts_nova_conductor_init | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.conductor.node_selector_key }}: {{ .Values.labels.conductor.node_selector_value }}
      containers:
        - name: nova-conductor
          image: {{ .Values.images.conductor }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.nova_conductor.requests.memory | quote }}
              cpu: {{ .Values.resources.nova_conductor.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.nova_conductor.limits.memory | quote }}
              cpu: {{ .Values.resources.nova_conductor.limits.cpu | quote }}
          {{- end }}
          command:
            - nova-conductor
            - --config-file
            - /etc/nova/nova.conf
          volumeMounts:
            - name: nova-etc
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf                    
{{ if $mounts_nova_conductor.volumeMounts }}{{ toYaml $mounts_nova_conductor.volumeMounts | indent 12 }}{{ end }}
      volumes:
        - name: nova-etc
          configMap:
            name: nova-etc
{{ if $mounts_nova_conductor.volumes }}{{ toYaml $mounts_nova_conductor.volumes | indent 8 }}{{ end }}
