apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: horizon
spec:
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: horizon
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "init",
            "image": "{{ .Values.images.entrypoint }}",
            "imagePullPolicy": "{{ .Values.images.pull_policy }}",
            "env": [
              {
                "name": "NAMESPACE",
                "value": "{{ .Release.Namespace }}"
              },
              {
                "name": "DEPENDENCY_SERVICE",
                "value": "memcached,keystone-api"
              },
              {
                "name": "COMMAND",
                "value": "echo done"
              }              
            ]
          }
        ]'        
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: horizon
          image: {{ .Values.images.horizon }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - bash
            - /tmp/start.sh
          ports:
            - containerPort: {{ .Values.network.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.port }}
          volumeMounts:
            - name: startsh
              mountPath: /tmp/start.sh
              subPath: start.sh
            - name: horizonconf
              mountPath: /etc/apache2/sites-enabled/000-default.conf
              subPath: horizon.conf
            - name: localsettings
              mountPath: /etc/openstack-dashboard/local_settings
              subPath: local_settings
          securityContext:
            runAsUser: 0              
      volumes:
        - name: startsh
          configMap:
            name: horizon-bin
        - name: horizonconf
          configMap:
            name: horizon-etc
        - name: localsettings
          configMap:
            name: horizon-etc
